using System.Globalization;

namespace Leander.Primitives.Parsing.Internal;

// Descriptions generated by the converter builders from their formats and styles.
internal static class FormatDescriptions
{
    // Standard formats are a letter, which says nothing to the reader, so they are shown as their pattern.
    private static readonly Dictionary<string, string> DateTimePatterns = new(StringComparer.Ordinal)
    {
        ["o"] = "yyyy-MM-ddTHH:mm:ss.fffffffK",
        ["O"] = "yyyy-MM-ddTHH:mm:ss.fffffffK",
        ["s"] = "yyyy-MM-ddTHH:mm:ss",
        ["u"] = "yyyy-MM-dd HH:mm:ssZ",
    };

    private static readonly Dictionary<string, string> TimeSpanPatterns = new(StringComparer.Ordinal)
    {
        ["c"] = "[-][d.]hh:mm:ss[.fffffff]",
        ["t"] = "[-][d.]hh:mm:ss[.fffffff]",
        ["T"] = "[-][d.]hh:mm:ss[.fffffff]",
        ["g"] = "[-][d:]h:mm:ss[.FFFFFFF]",
        ["G"] = "[-]d:hh:mm:ss.fffffff",
    };

    public static string DateTime(string[] formats, DateTimeStyles styles)
    {
        var description = $"A date and time as {Join(formats, DateTimePatterns)}";
        if (styles.HasFlag(DateTimeStyles.AssumeUniversal))
        {
            description += "; without an offset, UTC";
        }
        else if (styles.HasFlag(DateTimeStyles.AssumeLocal))
        {
            description += "; without an offset, local time";
        }

        return description + ".";
    }

    public static string TimeSpan(string[] formats, TimeSpanStyles styles)
    {
        var description = $"A duration as {Join(formats, TimeSpanPatterns)}";
        if (styles.HasFlag(TimeSpanStyles.AssumeNegative))
        {
            description += ", taken as negative";
        }

        // Without a format the converter can't be used anyway, but Build() doesn't throw.
        if (formats.Length > 0)
        {
            description += $", e.g. {System.TimeSpan.FromSeconds(30).ToString(formats[0], CultureInfo.InvariantCulture)}";
        }

        return description + ".";
    }

    private static string Join(string[] formats, Dictionary<string, string> patterns) =>
        string.Join(" or ", formats.Select(format => patterns.GetValueOrDefault(format, format)));
}
