<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Markdown documentation, contract files, example appsettings.json and contract comparisons for Leander.Configuration contracts.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Leander.Configuration\Leander.Configuration.csproj" />
  </ItemGroup>

</Project>
